import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { RefreshCw } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { ChartContainer, ChartTooltip, ChartTooltipContent, ChartLegend, ChartLegendContent } from "@/components/ui/chart";
import { LineChart, Line, XAxis, YAxis, CartesianGrid } from "recharts";

type Step = { event_type: string; events: number; users: number; browsers: number; visits: number };
type Usage = { trackingSince: string; updatedAt: string; steps: Step[]; daily: Array<{ day: string; opens: number; users: number; public_visits: number; joined: number }>; members: { active: number; ambassadors: number; new: number; updates: number }; referrals: { reached: number; started: number; continued: number }; dropoff: { openedWithoutChoice: number; formWithoutJoin: number; attemptWithoutJoin: number; returned: number } };
const labels: Record<string, string> = { home_viewed: "Tela inicial vista", card_viewed: "Destaque do Movimento visto", card_clicked: "Clique no destaque", public_viewed: "Página pública aberta", area_opened: "Área do Movimento aberta", introduction_viewed: "Apresentação vista", join_cta_clicked: "Interesse em participar", role_selected: "Papel escolhido", form_viewed: "Confirmação de adesão vista", join_started: "Tentativa de adesão", join_failed: "Falha de adesão", member_joined: "Adesão concluída", ambassador_joined: "Adesão como Embaixador", form_back: "Voltou sem confirmar", cause_selected: "Escolheu mensagem da causa", mural_viewed: "Mural visto", kit_viewed: "Kit visto", message_selected: "Versão do convite escolhida", invite_copied: "Convite copiado", whatsapp_share_started: "Abriu convite no WhatsApp", share_started: "Abriu compartilhamento", share_completed: "Compartilhamento confirmado pelo aparelho", share_cancelled: "Compartilhamento cancelado", share_failed: "Falha ao compartilhar", updates_enabled: "Ativou novidades", updates_disabled: "Desativou novidades" };
const config = { users: { label: "Pessoas na área", color: "hsl(var(--primary))" }, public_visits: { label: "Aberturas públicas", color: "hsl(var(--chart-2))" }, joined: { label: "Novas adesões medidas", color: "hsl(var(--chart-3))" } };
const dayLabel = (day: string) => day.slice(5).split("-").reverse().join("/");
export function MovementUsagePanel() {
  const [days, setDays] = useState("30");
  const [tests, setTests] = useState(false);
  const query = useQuery({ queryKey: ["movement-usage", days, tests], staleTime: 60_000, queryFn: async () => {
    const { data, error } = await supabase.rpc("admin_movement_usage", { _days: Number(days), _include_tests: tests });
    if (error) throw new Error("Não foi possível carregar o uso do Movimento.");
    return data as unknown as Usage;
  } });
  const data = query.data;
  return <section aria-label="Uso do Movimento" className="space-y-5 border-y border-border py-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Uso e adesão ao Movimento</h2><p className="mt-1 text-sm text-muted-foreground">Da descoberta ao convite e ao início de uma conversa.</p></div><div className="flex items-center gap-2"><Select value={days} onValueChange={setDays}><SelectTrigger className="w-40" aria-label="Período do Movimento"><SelectValue /></SelectTrigger><SelectContent>{[7, 30, 90].map(n => <SelectItem key={n} value={String(n)}>Últimos {n} dias</SelectItem>)}</SelectContent></Select><Button variant="outline" size="icon" aria-label="Atualizar uso do Movimento" disabled={query.isFetching} onClick={() => void query.refetch()}><RefreshCw className={query.isFetching ? "animate-spin" : ""} /></Button></div></div>
    <label className="flex items-center gap-3 text-sm"><Switch checked={tests} onCheckedChange={setTests} />Incluir administração e contas de demonstração</label>
    {query.isPending ? <p role="status" className="py-8 text-muted-foreground">Carregando uso…</p> : query.isError ? <div role="alert"><p>{query.error.message}</p><Button variant="outline" onClick={() => void query.refetch()}>Tentar novamente</Button></div> : data && <>
      <div className="border-l-2 border-primary pl-4 text-sm"><p className="font-semibold">Medição iniciada em {new Date(data.trackingSince).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" })}</p><p className="text-muted-foreground">Acessos anteriores não foram registrados e não podem ser recuperados. Dias anteriores aparecem sem medição.</p></div>
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Participantes ativos", data.members.active], ["Embaixadores ativos", data.members.ambassadors], ["Novos participantes no período", data.members.new], ["Recebem novidades", data.members.updates]].map(([label, value]) => <div key={label} className="border-l-2 border-border pl-4"><p className="text-3xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>)}</div>
      <ChartContainer config={config} className="h-[260px] w-full aspect-auto"><LineChart accessibilityLayer data={data.daily.map(d => ({ ...d, users: d.day < data.trackingSince.slice(0, 10) ? null : d.users, public_visits: d.day < data.trackingSince.slice(0, 10) ? null : d.public_visits, joined: d.day < data.trackingSince.slice(0, 10) ? null : d.joined }))}><CartesianGrid vertical={false} /><XAxis dataKey="day" tickFormatter={dayLabel} minTickGap={24} /><YAxis allowDecimals={false} width={30} /><ChartTooltip content={<ChartTooltipContent labelFormatter={v => dayLabel(String(v))} />} /><ChartLegend content={<ChartLegendContent />} />{Object.keys(config).map(key => <Line key={key} dataKey={key} stroke={`var(--color-${key})`} strokeWidth={2} dot={{ r: 3 }} connectNulls={false} isAnimationActive={false} />)}</LineChart></ChartContainer>
      <div className="overflow-x-auto"><table className="w-full text-sm"><caption className="text-left mb-3 font-semibold">Etapas no período · pessoas não são somadas entre etapas</caption><thead><tr className="text-left text-muted-foreground"><th className="py-2 pr-4">Etapa</th><th className="text-right px-3">Pessoas identificadas</th><th className="text-right px-3">Navegadores</th><th className="text-right pl-3">Ocorrências</th></tr></thead><tbody>{Object.entries(labels).map(([key, label]) => { const step = data.steps.find(s => s.event_type === key); return <tr key={key} className="border-t border-border"><td className="py-2 pr-4">{label}</td><td className="text-right px-3">{step?.users || 0}</td><td className="text-right px-3">{step?.browsers || 0}</td><td className="text-right pl-3">{step?.events || 0}</td></tr>; })}</tbody></table></div>
      <div className="grid gap-5 sm:grid-cols-2"><div><h3 className="font-semibold">Continuidade da adesão</h3><p className="mt-2 text-sm text-muted-foreground">Viram confirmação, sem adesão medida: <strong>{data.dropoff.formWithoutJoin}</strong></p><p className="text-sm text-muted-foreground">Tentaram aderir, sem conclusão medida: <strong>{data.dropoff.attemptWithoutJoin}</strong></p><p className="text-sm text-muted-foreground">Reabriram a área no período: <strong>{data.dropoff.returned}</strong></p></div><div><h3 className="font-semibold">Resultados dos convites no período</h3><p className="mt-2 text-sm text-muted-foreground">Navegadores que abriram indicação: <strong>{data.referrals.reached}</strong></p><p className="text-sm text-muted-foreground">Pessoas que começaram a conversar: <strong>{data.referrals.started}</strong></p><p className="text-sm text-muted-foreground">Pessoas que continuaram: <strong>{data.referrals.continued}</strong></p></div></div>
      <p className="text-xs text-muted-foreground">Copiar ou abrir o WhatsApp não comprova envio. Navegadores não equivalem a pessoas; acessos anônimos não permitem excluir testes não identificados. As etapas incluem visitantes e membros existentes, não representam uma taxa de conversão de uma mesma coorte.</p>
      <p className="text-xs text-muted-foreground">Consultado em {new Date(data.updatedAt).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" })} · horário de Brasília.</p>
    </>}
  </section>;
}