import { useEffect, useState } from "react";
import { Helmet } from "react-helmet-async";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight, Award, Check, HeartHandshake, Menu, MessageCircle, Route, Sprout, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import logoOlaAura from "@/assets/logo-ola-aura-horizontal.png";
import movementImage from "@/assets/movimento-ola-aura.jpg";
import { MOVEMENT_ACHIEVEMENTS, recordMovementReach } from "@/lib/movement";
import { supabasePortal } from "@/integrations/supabase/portal-client";

export default function Movement() {
  const [params] = useSearchParams();
  const [menuOpen, setMenuOpen] = useState(false);
  const [sharedBy, setSharedBy] = useState<string | null>(null);
  const [snapshot, setSnapshot] = useState<{ members: number; started: number; continued: number; mural: Array<{ id: string; title: string; body: string; member_name: string }> } | null>(null);
  const code = params.get("por");

  useEffect(() => {
    if (code) void recordMovementReach(code).then((result) => setSharedBy(result?.shared_by || null));
    void supabasePortal.functions.invoke("movement-public", { body: { action: "snapshot" } }).then(({ data }) => setSnapshot(data?.result || null));
  }, [code]);

  return <div className="movement-theme min-h-screen bg-background text-foreground">
    <Helmet><title>Movimento Olá Aura — Compreensão não deveria ser privilégio</title><meta name="description" content="Faça parte do Movimento Olá Aura e ajude compreensão, apoio e direção a chegarem a mais pessoas." /><meta property="og:title" content="Movimento Olá Aura" /><meta property="og:description" content="Compreender a si mesmo não deveria ser privilégio de poucos." /><meta property="og:type" content="website" /><meta name="twitter:card" content="summary_large_image" /></Helmet>
    <header className="absolute inset-x-0 top-0 z-30 border-b border-primary-foreground/15">
      <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/v2"><img src={logoOlaAura} alt="Olá Aura" className="h-8 w-auto brightness-0 invert sm:h-9" /></Link><nav className="hidden items-center gap-7 md:flex"><a href="#manifesto" className="text-sm font-semibold text-primary-foreground/75">Manifesto</a><a href="#como-participar" className="text-sm font-semibold text-primary-foreground/75">Como participar</a><a href="#conquistas" className="text-sm font-semibold text-primary-foreground/75">Conquistas</a><Button asChild variant="secondary"><Link to="/movimento/area">Fazer parte</Link></Button></nav><Button variant="ghost" size="icon" className="text-primary-foreground md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menu">{menuOpen ? <X /> : <Menu />}</Button></div>
      {menuOpen && <nav className="border-t border-primary-foreground/15 bg-foreground px-5 py-5 text-primary-foreground md:hidden"><div className="flex flex-col gap-4"><a href="#manifesto" onClick={() => setMenuOpen(false)}>Manifesto</a><a href="#como-participar" onClick={() => setMenuOpen(false)}>Como participar</a><a href="#conquistas" onClick={() => setMenuOpen(false)}>Conquistas</a><Button asChild variant="secondary"><Link to="/movimento/area">Fazer parte</Link></Button></div></nav>}
    </header>

    <main>
      <section className="relative min-h-[calc(100svh-1.5rem)] overflow-hidden bg-foreground text-primary-foreground md:min-h-[720px]">
        <img src={movementImage} alt="Pessoas reunidas pelo Movimento Olá Aura" width={1600} height={1000} className="absolute inset-0 h-full w-full object-cover object-[67%_center] md:object-center" />
        <div className="absolute inset-0 bg-gradient-to-t from-foreground via-foreground/65 to-foreground/20 md:bg-gradient-to-r md:from-foreground md:via-foreground/80 md:to-foreground/15" />
        <div className="relative mx-auto flex min-h-[calc(100svh-1.5rem)] max-w-7xl items-end px-5 pb-8 pt-28 sm:px-8 md:min-h-[720px] md:items-center md:pb-16"><div className="max-w-2xl"><p className="text-xs font-bold uppercase text-primary-foreground/70">Movimento Olá Aura</p><h1 className="mt-4 max-w-xl font-display text-[2.65rem] font-semibold leading-[1.03] sm:text-6xl md:mt-5 md:max-w-2xl md:text-7xl">Quando uma pessoa encontra direção, essa mudança pode chegar a muitas outras.</h1><p className="mt-4 max-w-xl text-base leading-relaxed text-primary-foreground/80 md:mt-6 md:text-lg">Compreender a si mesmo não deveria ser privilégio de poucos.</p>{sharedBy && <p className="mt-4 border-l-2 border-accent pl-4 text-sm text-primary-foreground/85 md:mt-5">{sharedBy} participa do Movimento e compartilhou esta possibilidade com você.</p>}<div className="mt-5 flex gap-3 md:mt-8"><Button asChild size="lg" variant="secondary" className="flex-1 sm:flex-none"><Link to="/movimento/area">Quero fazer parte <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline" className="hidden border-primary-foreground/35 bg-transparent text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground sm:inline-flex"><a href="#manifesto">Conhecer o Movimento</a></Button></div></div></div>
      </section>

      <section id="manifesto" className="py-20 sm:py-28"><div className="mx-auto max-w-5xl px-5 sm:px-8"><p className="text-xs font-bold uppercase text-primary">Por que existimos</p><div className="mt-5 grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><h2 className="font-display text-4xl font-semibold leading-tight sm:text-5xl">Muita gente ainda enfrenta tudo sozinha.</h2><div className="space-y-5 text-lg leading-relaxed text-muted-foreground"><p>Todo mundo atravessa momentos em que parece difícil compreender o que está sentindo, perceber por que certas situações continuam se repetindo ou encontrar um caminho possível.</p><p>A Olá Aura nasceu para tornar esse cuidado mais próximo da vida real: um lugar para conversar, aprofundar o que está vivendo, reconhecer padrões e encontrar direção.</p><p className="font-semibold text-foreground">Uma indicação pode parecer pequena para quem faz — mas pode chegar em um momento muito importante para quem recebe.</p></div></div></div></section>

      <section id="como-participar" className="border-y border-border bg-secondary/45 py-20"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="max-w-2xl"><p className="text-xs font-bold uppercase text-primary">Como participar</p><h2 className="mt-4 font-display text-4xl font-semibold">Você escolhe até onde quer ir com o Movimento.</h2><p className="mt-4 leading-relaxed text-muted-foreground">Fazer parte não cria nenhuma obrigação de divulgar. Ser Embaixador é um passo separado e sempre voluntário.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-2"><div className="bg-background p-7"><HeartHandshake className="h-7 w-7 text-primary"/><p className="mt-5 text-xs font-bold uppercase text-primary">Participante</p><h3 className="mt-2 font-display text-2xl font-semibold">Eu faço parte</h3><p className="mt-3 leading-relaxed text-muted-foreground">Apoie a causa, acompanhe o Movimento e escolha sua privacidade. Sem precisar compartilhar nada.</p><Button asChild variant="outline" className="mt-6"><Link to="/movimento/area">Quero fazer parte</Link></Button></div><div className="bg-background p-7"><MessageCircle className="h-7 w-7 text-primary"/><p className="mt-5 text-xs font-bold uppercase text-primary">Embaixador</p><h3 className="mt-2 font-display text-2xl font-semibold">Eu quero multiplicar</h3><p className="mt-3 leading-relaxed text-muted-foreground">Escolha compartilhar com verdade, receba seu link pessoal e acompanhe o impacto sem expor ninguém.</p><Button asChild className="mt-6"><Link to="/movimento/area?papel=embaixador">Quero ser Embaixador</Link></Button></div></div><div className="mt-12 grid gap-8 md:grid-cols-3">{[{ icon: HeartHandshake, title: "Escolha livre", text: "Você pode apenas fazer parte ou também atuar como Embaixador." }, { icon: MessageCircle, title: "Compartilhe sem pressão", text: "Como Embaixador, use seu link somente quando fizer sentido." }, { icon: Route, title: "Acompanhe o impacto", text: "Veja quem conheceu, começou e decidiu continuar, sem expor identidades." }].map(({icon: Icon,title,text}, index) => <div key={title} className="border-t-2 border-primary pt-5"><span className="text-xs font-bold text-primary">0{index+1}</span><Icon className="mt-6 h-7 w-7" /><h3 className="mt-4 font-display text-2xl font-semibold">{title}</h3><p className="mt-3 leading-relaxed text-muted-foreground">{text}</p></div>)}</div></div></section>

      <section id="conquistas" className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase text-primary">Reconhecimento</p><h2 className="mt-4 font-display text-4xl font-semibold">Conquistas que representam impacto, não vendas.</h2></div><p className="max-w-md text-sm leading-relaxed text-muted-foreground">Sem pódio e sem competição. Cada marco celebra uma contribuição verdadeira.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{MOVEMENT_ACHIEVEMENTS.map((item) => <div key={item.id} className="bg-background p-6"><Award className="h-6 w-6 text-primary" /><h3 className="mt-5 font-display text-xl font-semibold">{item.name}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{item.description}</p></div>)}</div></div></section>

      <section className="bg-foreground py-16 text-primary-foreground"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="grid gap-8 text-center sm:grid-cols-3">{snapshot && snapshot.members >= 10 ? <><div><p className="font-display text-4xl">{snapshot.members}</p><p className="mt-2 text-sm text-primary-foreground/60">participantes</p></div><div><p className="font-display text-4xl">{snapshot.started}</p><p className="mt-2 text-sm text-primary-foreground/60">pessoas começaram</p></div><div><p className="font-display text-4xl">{snapshot.continued}</p><p className="mt-2 text-sm text-primary-foreground/60">decidiram continuar</p></div></> : <div className="sm:col-span-3"><Sprout className="mx-auto h-7 w-7 text-accent" /><h2 className="mt-4 font-display text-3xl">Este movimento está apenas começando.</h2><p className="mt-2 text-primary-foreground/60">E você pode fazer parte desde o início.</p></div>}</div></div></section>

      {snapshot?.mural && snapshot.mural.length > 0 && <section className="py-20"><div className="mx-auto max-w-6xl px-5 sm:px-8"><p className="text-xs font-bold uppercase text-primary">Mural do Movimento</p><h2 className="mt-4 font-display text-4xl font-semibold">Histórias e marcos que merecem ser reconhecidos.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{snapshot.mural.map((item) => <article key={item.id} className="rounded-lg border border-border p-5"><p className="text-xs font-bold text-primary">{item.member_name}</p><h3 className="mt-3 font-display text-xl font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{item.body}</p></article>)}</div></div></section>}

      <section className="border-t border-border py-20 text-center"><div className="mx-auto max-w-2xl px-5"><Users className="mx-auto h-7 w-7 text-primary" /><h2 className="mt-5 font-display text-4xl font-semibold">Você não precisa alcançar milhares de pessoas.</h2><p className="mt-4 text-lg text-muted-foreground">Se escolher ser Embaixador, apresentar uma possibilidade à pessoa certa já pode importar muito.</p><Button asChild size="lg" className="mt-7"><Link to="/movimento/area?papel=embaixador">Quero ser Embaixador <ArrowRight /></Link></Button></div></section>
    </main>
    <footer className="border-t border-border py-8"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-5 text-sm text-muted-foreground sm:flex-row"><Link to="/v2"><img src={logoOlaAura} alt="Olá Aura" className="h-10 w-auto" /></Link><p>Movimento Olá Aura · participação livre, respeitosa e sem pressão.</p></div></footer>
  </div>;
}
