ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS voice_mode TEXT NOT NULL DEFAULT 'auto',
  ADD COLUMN IF NOT EXISTS voice_mode_set_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS capsule_state_set_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS capsule_prompt_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS is_audio BOOLEAN NOT NULL DEFAULT false;